version: '3'
services:
  mall-admin:
    image: java:8
    volumes:
      - ./logs/app/mall-admin:/var/logs
      - /etc/localtime:/etc/localtime
      - ${SOURCE_DIR}:/var/www/:rw
    working_dir: /var/www
    command: java -jar -Dspring.profiles.active=prod /var/www/mall-admin/target/mall-admin-1.0-SNAPSHOT.jar
    ports:
      - 8080:8080
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - mysql:db #可以用db这个域名访问mysql服务
  mall-search:
    image: java:8
    container_name: mall-search
    ports:
      - 8081:8081
    volumes:
      - ./logs/app/mall-search:/var/logs
      - /etc/localtime:/etc/localtime
      - ${SOURCE_DIR}:/var/www/:rw
    working_dir: /var/www
    command: java -jar -Dspring.profiles.active=prod /var/www/mall-search/target/mall-search-1.0-SNAPSHOT.jar
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
      - mysql:db #可以用db这个域名访问mysql服务
  mall-portal:
    image: java:8
    container_name: mall-portal
    ports:
      - 8085:8085
    volumes:
      - ./logs/app/mall-portal:/var/logs
      - /etc/localtime:/etc/localtime
      - ${SOURCE_DIR}:/var/www/:rw
    working_dir: /var/www
    command: java -jar -Dspring.profiles.active=prod /var/www/mall-portal/target/mall-portal-1.0-SNAPSHOT.jar
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - redis:redis #可以用redis这个域名访问redis服务
      - mongo:mongo #可以用mongo这个域名访问mongo服务
      - mysql:db #可以用db这个域名访问mysql服务
      - rabbitmq:rabbit #可以用rabbit这个域名访问rabbitmq服务

networks:
  default:
    external:
      name: devpos_default